"""adding a boolean input

Revision ID: aef38d739e67
Revises: 
Create Date: 2024-06-06 20:27:40.887538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef38d739e67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historys', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historys', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
